export const GET_FILESYSTEM_ENTRIES_REQUESTING =
  "GET_FILESYSTEM_ENTRIES_REQUESTING";
export const GET_FILESYSTEM_ENTRIES_SUCCESS = "GET_FILESYSTEM_ENTRIES_SUCCESS";
export const SET_ENTRY_AS_SELECTED = "SET_ENTRY_AS_SELECTED";
export const SET_ENTRY_AS_SELECTED_SUCCESS = "SET_ENTRY_AS_SELECTED_SUCCESS";
export const SET_ENTRY_AS_EDITING_SUCCESS = "SET_ENTRY_AS_EDITING";
export const DELETE_ENTRY = "DELETE_ENTRY";
export const DELETE_ENTRY_SUCCESS = "DELETE_ENTRY_SUCCESS";
export const OPEN_FILE_SUCCESS = "OPEN_FILE_SUCCESS";
export const OPEN_CONTEXT_MENU_SUCCESS = "OPEN_CONTEXT_MENU_SUCCESS";
export const SHOW_PROPERTIES_DIALOG_SUCCESS = "SHOW_PROPERTIES_DIALOG_SUCCESS";
export const CLOSE_NOVA_SUCCESS = "CLOSE_NOVA_SUCCESS";
export const MINIMIZE_NOVA_SUCCESS = "MINIMIZE_NOVA_SUCCESS";
export const MAXIMIZE_NOVA_SUCCESS = "MAXIMIZE_NOVA_SUCCESS";
